### ISSUE TITLE
生成的文件只能整个词搜索

### ISSUE THREAD

**Issue by heatfx** [bosbyj/sphinx.search.zh_CN#1]
搜索一句话里的一个单词，总是显示 “没有任何文档匹配您的搜索”
搜索一整句话就可以检出。

**Comment by heatfx** [comment]
代码并不存在问题！
折腾了挺长时间，最终搞定了。
在python2.7 和python3.4两个不同版本都安装成功，具体的解决办法[看这里](http://www.jianshu.com/p/d99f1b399ddc)
http://www.jianshu.com/p/d99f1b399ddc

**Comment by bosbyj** [comment]
恭喜！这个东西有一阵子了，当时版本直接安装就可以用的。可能是sphinx更新了吧。
