### ISSUE TITLE
sphinx 是搜索引擎还是文档生成器

### ISSUE THREAD

**Issue by zengfanfan** [bosbyj/sphinx.search.zh_CN#2]
这个项目的sphinx指的是搜索引擎还是文档生成器？

如果是搜索引擎的话，没有Python27\Lib\site-packages\sphinx\search目录啊
——不是用PIP 安装的，而是RPM

**Comment by bosbyj** [comment]
指的是 www.pocoo.org/projects/sphinx/
这个项目。
